language: python

python:
  - "3.7-dev"

services:
  - mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE okoa_farmer_db;'
#  - python3 migrate.py db init
#  - python3 migrate.py db migrate
#  - python3 migrate.py db upgrade


script:
  - python manage.py test
