language: python

python:
  - "3.7"

services:
  - mysql

install:
  - pip install -r requirements.txt

before_script:
   ############### working connection to MySQL Database #################################
    - mysql -e 'CREATE DATABASE okoa_farmer_db;'
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('Masaki2017$$') WHERE user='root';\nFLUSH PRIVILEGES;\n"
    - mysql -u root -p'Masaki2017$$' -e 'show databases'
    - sudo mysql -e 'SHOW DATABASES;'
    - sudo mysql -e 'USE okoa_farmer_db;show tables;'
    - sudo mysql --version

script:
  - python -m pytest tests/
