language: python
python:
  -"3.8"
#install:
#  -"pip3 install pytest"
#  -"pip3 install -r requirements.txt"
#script: python3 -m pytest tests/


# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "python manage.py test"
