language: python

python:
  - "3.7"

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install pytest

before_script:
  - echo "USE mysql;\nUPDATE user SET password='Masaki2017$$' WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root -pMasaki2017$$
  - mysql -e 'CREATE DATABASE okoa_farmer_db;'
  - sudo mysql -e 'select database();'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE okoa_farmer_db;'
  - sudo mysql -e 'select database();'
  - sudo mysql --version
#  - python3 migrate.py db init
#  - python3 migrate.py db migrate
#  - python3 migrate.py db upgrade


script:
  - python -m pytest tests/
