language: python

python:
  - "3.7"

services:
  - mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE okoa_farmer_db;'
#  - sudo mysql -e 'select database();'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE okoa_farmer_db;'
#  - sudo mysql -e 'select database();'
  - sudo mysql --version
#  - python migrate.py db init
#  - python migrate.py db migrate
#  - python migrate.py db upgrade


script:
  - python -m pytest tests/
