language: python

python:
  - "3.7"

services:
  - mysql

install:
  - pip install -r requirements.txt

before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('Masaki2017$$') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE okoa_farmer_db;'
  - sudo mysql -uroot -pMasaki2017$$
#  - sudo mysql -e 'select database();'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE okoa_farmer_db;'
#  - sudo mysql -e 'select database();'
  - sudo mysql --version
#  - python migrate.py db init
#  - python migrate.py db migrate
#  - python migrate.py db upgrade


script:
  - python -m pytest tests/
